services:
  - type: web
    name: smart-farmer-dss
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: OPENWEATHER_API_KEY
        sync: false

